package movie;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Button;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
/**
 *
 * @author NITK
 */
/*class Guest extends JFrame{
   JLabel UserName,EmailID;
   JTextField TUserName,TEmailID;
   Button OK;
   Guest()
   {
       super("Guest Login");
   }
   void Show()
   {
       this.setTitle(" Guest Login");
       this.setBounds(100,230,350,400);
       this.setLayout(new FlowLayout());
      
       UserName = new JLabel("User Name:");
       EmailID= new JLabel("Email ID   :");
       TUserName=new JTextField(20);
       TEmailID=new JTextField(10);
       OK=new Button("OK");
       
       this.add(UserName);
       this.add(TUserName);
       this.add(EmailID);
       this.add(TEmailID);
       this.add(OK);
       
       
       ButtonHandlerOK listener=new ButtonHandlerOK();
       OK.addActionListener(listener);
        this.setVisible(true);
       
     }
   class ButtonHandlerOK implements ActionListener
{
    @Override
    public void actionPerformed(ActionEvent e){
        dispose();
       JOptionPane.showMessageDialog(null, "Successfully logged in as a guest user");
         JFrame ap = new guestlogin();
    ap.setVisible(true);
}

}
}*/

/*class Admin extends JFrame{
      JLabel AdminID,Adminpass;
   JTextField TID;
   JPasswordField Pass;
   Button LOGIN;
   Admin()
   {
       super("Admin Login");
   }
   void Show()
   {
       this.setTitle("Admin Login");
       this.setBounds(100,230,350,400);
       this.setLayout(new FlowLayout());
      
       AdminID = new JLabel("Admin ID:");
       Adminpass= new JLabel("Admin Password   :");
       TID=new JTextField(20);
       Pass=new JPasswordField(20);
       LOGIN=new Button("LOGIN");
       
       this.add(AdminID);
       this.add(TID);
       this.add(Adminpass);
       this.add(Pass);
       this.add(LOGIN);
       
       
       ButtonHandlerOK listener=new ButtonHandlerOK();
       LOGIN.addActionListener(listener);
        this.setVisible(true);
       
     }
class ButtonHandlerOK implements ActionListener
{
    @Override
    public void actionPerformed(ActionEvent e){
        dispose();
      JOptionPane.showMessageDialog(null, "Successfully logged in as an administrator");
       
    JFrame ap = new AdminPage();
    ap.setVisible(true);
}
}
}*/






public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 753, 450));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 753, 450));
        setMinimumSize(new java.awt.Dimension(753, 450));
        setResizable(false);
        getContentPane().setLayout(null);

        jLayeredPane1.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setFont(new java.awt.Font("Bangla Sangam MN", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("    Login as:");
        jLayeredPane1.add(jLabel2);
        jLabel2.setBounds(100, 10, 90, 19);

        jButton1.setFont(new java.awt.Font("Andale Mono", 0, 18)); // NOI18N
        jButton1.setText("ADMINISTRATOR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton1);
        jButton1.setBounds(50, 40, 216, 28);

        jButton2.setFont(new java.awt.Font("Andale Mono", 0, 18)); // NOI18N
        jButton2.setText("GUEST ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton2);
        jButton2.setBounds(50, 80, 216, 33);

        getContentPane().add(jLayeredPane1);
        jLayeredPane1.setBounds(210, 120, 330, 110);

        jLabel6.setFont(new java.awt.Font("American Typewriter", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("MOVIE SUCCESS PREDICTOR");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(90, 20, 570, 50);

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movie/red-carpet-curtains-grand-opening-16075025.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-20, 0, 800, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        JFrame gl=new guestlogin();
        gl.setLocationRelativeTo(null);
        gl.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        JFrame al=new adminlogin();
        al.setLocationRelativeTo(null);
       al.setVisible(true);
       // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NewJFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
